package com.example.flashcard_project.utils;

public enum Action {
    INSERT_NET,
    GET_ALL_NET,
    SIGN_UP_NET,
    SIGN_IN_NET,
    CHECK_USER_TOKEN_VALIDITY_NET,

    UPDATE_DB,
    INSERT_DB,
    INSERT_ALL_DB,
    GET_ALL_DB,
    DELETE_ALL,
    INSERT_ALL_USER_CARD_LEVEL,
    GET_CARDS_BY_UID_AND_LEVEL,
    UPDATE_LAST_REVIEWED,
    UPDATE_LEVEL_UP,
    UPDATE_LEVEL_DOWN,
    GET_USER_CARD_LEVELS_BY_LEVEL_AND_UID,
    GET_ALL_BY_IDS,
    GET_USER_BY_ID
}
